version: '3.8'
services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./cmd/api/.env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres